### ISSUE TITLE
Compatibility issue with Android plugin 4.0.0

### ISSUE THREAD

**Issue by pengdev** [mapbox/android-sdk-versions-plugin#21]
It seems there is an incompatibility issue with the `android-sdk-versions-plugin` and gradle plugin 4.0.0, the error is printed as follows:
```
Cannot cast object 'task ':MapboxGLAndroidSDK:generateDebugBuildConfig' property 'versionCode'' with class 'org.gradle.api.internal.provider.DefaultProperty' to class 'java.lang.Integer'
```
cc @harvsu

_Originally posted by @pengdev in https://github.com/mapbox/mapbox-gl-native-android/pull/408_

**Comment by nkukday** [comment]
https://github.com/mapbox/android-sdk-versions-plugin/releases/tag/sdkver-1.1.0
