### ISSUE TITLE
🐞 1.1.1 is unresolvable 

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/android-sdk-versions-plugin#33]
The `v1.1.1` has been released to the Mapbox's Maven hosting service, but it was pushed with an updated group ID from:
```
com.mapbox.mapboxsdk:mapbox-android-sdk-versions
```
to
```
com.mapbox.gradle.plugins:mapbox-android-sdk-versions
```

however, the package was not updated in https://github.com/mapbox/android-sdk-versions-plugin/blob/8db71bf1d09f218c5c7da3d537152af8fe9a10ee/gradle/artifact-settings.gradle#L2

which breaks the compatibility:
```
      > Could not resolve com.mapbox.gradle.plugins:mapbox-android-sdk-versions:1.1.1.
         > inconsistent module metadata found. Descriptor: com.mapbox.mapboxsdk:mapbox-android-sdk-versions:1.1.1 Errors: bad group: expected='com.mapbox.gradle.plugins' found='com.mapbox.mapboxsdk'
```

We need to either re-upload with an updated group ID or revert the change.

cc @mr1sunshine @tarigo @tobrun

**Comment by mr1sunshine** [comment]
Fixed by https://github.com/mapbox/api-downloads/pull/754
